spring:
  application:
    name: config-server
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      server:
        git:
          uri: https://github.com/khoffy/mcommerce-config-repo.git
server: # every Edge Microservice port is going to start with 91
  port: 9101



